#!/bin/bash

case $(uname -s) in
  Linux)
    echo "Enter Docker container..."
    exec docker run \
      --rm \
      --interactive --tty \
      --device /dev/kvm \
      --user $(id -u) \
      --security-opt label=disable \
      --workdir $PWD \
      --mount "type=bind,source=$PWD,destination=$PWD" \
      --entrypoint /bin/bash \
      godebos/debos
    ;;
  *)
    echo "Not supported: $(uname -s)"
    exit 1
  ;;
esac
