#!/bin/bash

CURDIR="$PWD"

case $(uname -s) in
  Linux)
    echo "Enter Docker container..."
    exec docker run \
      --rm \
      --interactive --tty \
      --device /dev/kvm \
      --user $(id -u) \
      --security-opt label=disable \
      --workdir "${CURDIR}" \
      --mount "type=bind,source=${CURDIR},destination=${CURDIR}" \\
      --entrypoint /bin/bash
      godebos/debos \
    ;;
  *)
    echo "Not supported: $(uname -s)"
    exit 1
  ;;
esac
